<?php
########################################################################
# Extension Manager/Repository config file for ext: "ssch_beratungsstellendatenbank"
#
# Auto generated by Extension Builder 2011-11-17
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Beratungsstellensuche',
    'description' => 'Beratungsstellensuche der BZgA',
    'category' => 'plugin',
    'author' => 'Sebastian Schreiber',
    'author_email' => 'me@schreibersebastian.de',
    'author_company' => '',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'beta',
    'internal' => '',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 1,
    'lockType' => '',
    'version' => '6.2.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2.10-6.99.99',
            'static_info_tables' => '6.0.0-',
            'scheduler' => '6.2',
        ),
        'conflicts' => array(),
    ),
);