<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'Zend\\Diactoros\\' => array($vendorDir . '/zendframework/zend-diactoros/src'),
    'Symfony\\Polyfill\\Php70\\' => array($vendorDir . '/symfony/polyfill-php70'),
    'Symfony\\Component\\Serializer\\' => array($vendorDir . '/symfony/serializer'),
    'Symfony\\Component\\PropertyAccess\\' => array($vendorDir . '/symfony/property-access'),
    'Symfony\\Component\\Inflector\\' => array($vendorDir . '/symfony/inflector'),
    'Symfony\\Component\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Ivory\\JsonBuilder\\' => array($vendorDir . '/egeloen/json-builder/src'),
    'Ivory\\HttpAdapter\\' => array($vendorDir . '/egeloen/http-adapter/src'),
    'Ivory\\GoogleMap\\' => array($vendorDir . '/egeloen/google-map/src'),
);
