cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_api/doc_core_api/doc/                        ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_cgl/doc_core_cgl/doc/                        ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_cgl/doc_core_cgl_fr/doc/                     ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_cgl/doc_core_cgl_ru/doc/                     ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_inside/doc_core_inside/doc/                  ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_services/doc_core_services/doc/              ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_skinning/doc_core_skinning/doc/              ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_tca/doc_core_tca/doc/                        ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_ts/doc_core_ts/doc/                          ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_tsconfig/doc_core_tsconfig/doc/              ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_tsconfig/doc_core_tsconfig_fr/doc/           ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_tsconfig/doc_core_tsconfig_ru/doc/           ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_tsref/doc_core_tsref/doc/                    ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_tsref/doc_core_tsref_fr/doc/                 ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_tsref/doc_core_tsref_ru/doc/                 ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_guide_admin/doc_guide_admin/doc/                  ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_guide_install/doc_guide_install/doc/              ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_guide_install/doc_guide_install_da/doc/           ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_guide_install/doc_guide_install_fr/doc/           ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_guide_install/doc_guide_install_ja/doc/           ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_guide_install/doc_guide_install_ru/doc/           ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_guide_l10n/doc_guide_l10n/doc/                    ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_guide_l10n/doc_guide_l10n_ru/doc/                 ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_guide_security/doc_guide_security/doc/            ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_indexed_search/doc/                               ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_template/doc/                                     ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_editors/doc_tut_editors_basicreference/doc/   ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_editors/doc_tut_editors_manual/doc/           ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_editors/doc_tut_editors_partsnotinmanual/doc/ ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_ts45/doc_tut_ts45/doc/                        ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_ts45/doc_tut_ts45_da/doc/                     ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_ts45/doc_tut_ts45_de/doc/                     ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_ts45/doc_tut_ts45_it/doc/                     ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_ts45/doc_tut_ts45_ja/doc/                     ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_ts45/doc_tut_ts45_nl/doc/                     ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_ts45/doc_tut_ts45_ru/doc/                     ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/official_template/DocBook/docs/                       ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/official_template/OpenOffice/                         ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/TCA-Reference-4-6/                                    ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/tsref-4-6/                                            ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_quickstart/doc_tut_quickstart/doc/            ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_quickstart/doc_tut_quickstart_da/doc/         ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_quickstart/doc_tut_quickstart_de/doc/         ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_quickstart/doc_tut_quickstart_fr/doc/         ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_quickstart/doc_tut_quickstart_ja/doc/         ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_quickstart/doc_tut_quickstart_nl/doc/         ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_quickstart/doc_tut_quickstart_ro/doc/         ;    make  clean ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_quickstart/doc_tut_quickstart_ru/doc/         ;    make  clean ;   make  html

cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4

