cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_api/doc_core_api/doc/                        ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_cgl/doc_core_cgl/doc/                        ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_cgl/doc_core_cgl_fr/doc/                     ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_cgl/doc_core_cgl_ru/doc/                     ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_inside/doc_core_inside/doc/                  ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_services/doc_core_services/doc/              ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_skinning/doc_core_skinning/doc/              ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_tca/doc_core_tca/doc/                        ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_ts/doc_core_ts/doc/                          ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_tsconfig/doc_core_tsconfig/doc/              ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_tsconfig/doc_core_tsconfig_fr/doc/           ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_tsconfig/doc_core_tsconfig_ru/doc/           ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_tsref/doc_core_tsref/doc/                    ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_tsref/doc_core_tsref_fr/doc/                 ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_core_tsref/doc_core_tsref_ru/doc/                 ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_guide_admin/doc_guide_admin/doc/                  ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_guide_install/doc_guide_install/doc/              ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_guide_install/doc_guide_install_da/doc/           ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_guide_install/doc_guide_install_fr/doc/           ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_guide_install/doc_guide_install_ja/doc/           ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_guide_install/doc_guide_install_ru/doc/           ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_guide_l10n/doc_guide_l10n/doc/                    ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_guide_l10n/doc_guide_l10n_ru/doc/                 ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_guide_security/doc_guide_security/doc/            ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_indexed_search/doc/                               ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_template/doc/                                     ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_editors/doc_tut_editors_basicreference/doc/   ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_editors/doc_tut_editors_manual/doc/           ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_editors/doc_tut_editors_partsnotinmanual/doc/ ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_ts45/doc_tut_ts45/doc/                        ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_ts45/doc_tut_ts45_da/doc/                     ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_ts45/doc_tut_ts45_de/doc/                     ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_ts45/doc_tut_ts45_it/doc/                     ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_ts45/doc_tut_ts45_ja/doc/                     ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_ts45/doc_tut_ts45_nl/doc/                     ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_ts45/doc_tut_ts45_ru/doc/                     ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/official_template/DocBook/docs/                       ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/official_template/OpenOffice/                         ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/TCA-Reference-4-6/                                    ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/tsref-4-6/                                            ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_quickstart/doc_tut_quickstart/doc/            ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_quickstart/doc_tut_quickstart_da/doc/         ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_quickstart/doc_tut_quickstart_de/doc/         ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_quickstart/doc_tut_quickstart_fr/doc/         ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_quickstart/doc_tut_quickstart_ja/doc/         ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_quickstart/doc_tut_quickstart_nl/doc/         ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_quickstart/doc_tut_quickstart_ro/doc/         ; touch source/index.rst ;   make  html
cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4/doc_tut_quickstart/doc_tut_quickstart_ru/doc/         ; touch source/index.rst ;   make  html

cd /home/mbless/HTDOCS/DOCROOT_SRC/TYPO3v4
